finish supporting expressions repeaters
BuildFire/sdk pull request #751
Opened 2023-05-15 17:57 UTC by ahasnawi

Finish supporting expressions repeaters

2023-05-15 19:33 UTC, mas-iota requested changes

2023-05-15 19:33 UTC, mas-iota commented on scripts/dynamic/dynamicEngine.js
> +			let [loopVar, arrayName] = repeatAttr.split(' in ');
let [variable, array]

2023-05-15 19:33 UTC, mas-iota commented on scripts/dynamic/dynamicEngine.js
> +				console.error(err);
console.error(`Error occurred while evaluating repeater : ${err}`)

2023-06-01 21:18 UTC, mas-iota approved these changes

2023-06-13 19:43 UTC, bkalaldeh approved these changes

2023-06-13 19:43 UTC, merged