fix imagelib on plugin tester
BuildFire/sdk pull request #766
Opened 2023-07-04 21:59 UTC by mhd-rawashdah

2023-07-06 14:58 UTC, bkalaldeh requested changes

2023-07-06 14:58 UTC, bkalaldeh commented on pluginTester/scripts/overrides.js
> +		showAIImages: false
should be 'showAiImages' to stay consistent with 'AiAPI'

2023-07-11 19:11 UTC, mhd-rawashdah commented on pluginTester/scripts/overrides.js
> +		showAIImages: false
`showAIImagea` property already created  like this while ago and it's  on production @bkalaldeh

2023-07-12 12:29 UTC, bkalaldeh commented on pluginTester/scripts/overrides.js
> +		showAIImages: false
Where is the issue in fixing it on production ?

2023-07-23 23:43 UTC, closed without merging